import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/app/myComponents/header";
import { AuthProvider } from "./contexts/AuthContext";
//import Footer from "./myComponents/footer";
import { GuicheProvider } from "./contexts/guicheContext";
import { TotalSenhasProvider } from "./contexts/totalSenhasContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gerênciador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-screen antialiased box-border  bg-[#ebeff5] overflow-x-hidden `}
      >
        <AuthProvider>
          <GuicheProvider>
            <TotalSenhasProvider>
              <div className=" sticky top-0 ">
                <Header />
              </div>
              {/* h-[calc(100vh-6.25rem)] */}
              <main className=" flex justify-center items-center my-auto box-border   ">
                <div className="   ">{children}</div>
              </main>
            </TotalSenhasProvider>
          </GuicheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
