import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/app/myComponents/header";
import { AuthProvider } from "./contexts/AuthContext";
//import Footer from "./myComponents/footer";
import { GuicheProvider } from "./contexts/guicheContext";
import { TotalSenhasProvider } from "./contexts/totalSenhasContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gerênciador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased   bg-[#ebeff5]`}
      >
        <AuthProvider>
          <GuicheProvider>
            <TotalSenhasProvider>
              <div className=" ">
                <Header />
                {/* h-[calc(100vh-6.25rem)] */}
                <main className=" flex justify-center items-center my-auto  ">
                  <div className="  scale-95 ">{children}</div>
                </main>
              </div>
            </TotalSenhasProvider>
          </GuicheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
